import { Plan, Phone, CarrierType } from './types';

export const SAMPLE_PLANS: Plan[] = [
  {
    id: 'p1',
    provider: '이지모바일',
    carrier: CarrierType.LGU,
    name: '데이터 프리덤 11GB+',
    data: '11GB + 일2GB + 3Mbps',
    voice: '기본제공',
    message: '기본제공',
    price: 15400,
    originalPrice: 38000,
    promoMonths: 7,
    tags: ['베스트셀러', '데이터무제한'],
  },
  {
    id: 'p2',
    provider: '모빙',
    carrier: CarrierType.SKT,
    name: 'SKT망 가성비 5GB',
    data: '5GB + 1Mbps',
    voice: '200분',
    message: '100건',
    price: 4400,
    originalPrice: 12000,
    promoMonths: 6,
    tags: ['가성비', '초특가'],
  },
  {
    id: 'p3',
    provider: 'kt M모바일',
    carrier: CarrierType.KT,
    name: '모두다 맘껏 100GB+',
    data: '100GB + 5Mbps',
    voice: '기본제공',
    message: '기본제공',
    price: 38900,
    originalPrice: 45000,
    tags: ['헤비유저', '영상매니아'],
  },
  {
    id: 'p4',
    provider: '티플러스',
    carrier: CarrierType.SKT,
    name: '완전마음껏 7GB+',
    data: '7GB + 1Mbps',
    voice: '기본제공',
    message: '기본제공',
    price: 9900,
    originalPrice: 24000,
    promoMonths: 12,
    tags: ['1만원이하', '학생추천'],
  },
  {
    id: 'p5',
    provider: '프리티',
    carrier: CarrierType.LGU,
    name: '든든한 평생요금제',
    data: '1GB',
    voice: '100분',
    message: '100건',
    price: 1100,
    originalPrice: 1100,
    tags: ['평생할인', '서브폰'],
  },
  {
    id: 'p6',
    provider: '이야기모바일',
    carrier: CarrierType.KT,
    name: '데이터 15GB+100분',
    data: '15GB + 3Mbps',
    voice: '100분',
    message: '100건',
    price: 13500,
    originalPrice: 28000,
    promoMonths: 6,
    tags: ['데이터중심', '통화적음'],
  },
];

export const SAMPLE_PHONES: Phone[] = [
  {
    id: 'ph1',
    name: 'iPhone 15 Pro',
    manufacturer: 'Apple',
    price: 1550000,
    imageUrl: 'https://picsum.photos/400/500?random=1',
    features: ['티타늄 디자인', 'A17 Pro 칩', '동작 버튼'],
    colors: ['내추럴 티타늄', '블루 티타늄', '화이트', '블랙'],
    badge: 'NEW'
  },
  {
    id: 'ph2',
    name: 'Galaxy S24 Ultra',
    manufacturer: 'Samsung',
    price: 1698400,
    imageUrl: 'https://picsum.photos/400/500?random=2',
    features: ['갤럭시 AI', '티타늄 프레임', '2억 화소 카메라'],
    colors: ['티타늄 그레이', '티타늄 옐로우', '티타늄 바이올렛'],
    badge: 'AI Phone'
  },
  {
    id: 'ph3',
    name: 'Galaxy Z Flip 5',
    manufacturer: 'Samsung',
    price: 1150000,
    imageUrl: 'https://picsum.photos/400/500?random=3',
    features: ['플렉스 윈도우', '콤팩트 디자인', '셀피 최적화'],
    colors: ['민트', '라벤더', '크림', '그라파이트'],
  },
  {
    id: 'ph4',
    name: 'iPhone 13 mini',
    manufacturer: 'Apple',
    price: 750000,
    imageUrl: 'https://picsum.photos/400/500?random=4',
    features: ['한 손 조작', '듀얼 카메라', 'A15 Bionic'],
    colors: ['핑크', '스타라이트', '미드나이트'],
    badge: '특가'
  }
];